### ISSUE TITLE
[description] Description not filled in

### ISSUE THREAD

**Issue by jodeck80** [SoftwareEngineeringToolDemos/FSE-2014-ConceptCloud#1]
Issue for criteria:

At the top of the page, is a project description filled in? [description]

**Comment by gauri145** [comment]
A more detailed description than earlier has been added now.

**Comment by jodeck80** [comment]
@gauri145 The description at the top of the repository still needs to be updated. You can access it by clicking edit next to the website that was added to the very top of the page.

**Comment by gauri145** [comment]
Short description for website has been added now
