### ISSUE TITLE
[vm-youtube] Video not in VM

### ISSUE THREAD

**Issue by jodeck80** [SoftwareEngineeringToolDemos/FSE-2014-ConceptCloud#10]
Issue for Criteria:

VM contains a link to Youtube video on the desktop that shows how to use the tool in the VM.

Video does not show how tool is operated from VM. Also, link should be able to be double clicked from desktop to access video, rather than copying link from text file.

**Comment by gauri145** [comment]
The tool is immediately visible when the VM is opened. The video provides details on how to use the various features of the tool. Hence, the video is sufficient for the user to be able to use the tool. 

The link can be used with a double click from Desktop. The textfile with video link is also kept for reference.
