### ISSUE TITLE
[vm-install] Double Click Execute Unclear

### ISSUE THREAD

**Issue by jodeck80** [SoftwareEngineeringToolDemos/FSE-2014-ConceptCloud#11]
Issue for criteria:

Installation.txt on the desktop that says how to install the tool from scratch.

The issue here is minor. "just change File->Edit->Ask always for running executable" is unclear where it points to to access "File->Edit". Specifically, what program do you access "File-Edit" in?

**Comment by gauri145** [comment]
It is accessed through File Explorer. The word has been added now to the readme.
