### ISSUE TITLE
[vm-other] Chrome Browser not installed

### ISSUE THREAD

**Issue by jodeck80** [SoftwareEngineeringToolDemos/FSE-2014-ConceptCloud#13]
It was recommended to use the Google Chrome browser, but it is not installed. It should be installed and placed on the launcher if it is the best browser to use. It is also recommended to increase the heap size, can this be done so the user doesn't have to? This VM will only be used to run conceptCloud.

**Comment by gauri145** [comment]
Chrome browser was already installed but it was not added to the launcher. Now it has been added to the launcher. The heap size was already increased using the following command export _JAVA_OPTIONS="-Xms800m -Xmx1500m".
