### ISSUE TITLE
[vm-other] VM login and PW

### ISSUE THREAD

**Issue by jodeck80** [SoftwareEngineeringToolDemos/FSE-2014-ConceptCloud#15]
This may be another non issue, and should be coordinated with the professor just to make sure we are consistent. Should the VM user name and password be provided in a file on the desktop, or readme? This would allow users of the VM to download other applications if they want to use it with the tool.

**Comment by gauri145** [comment]
As discussed by the professor, in today's lecture, the username and password should be the same and provided on the desktop of the vm. They will be required only if vm is explicitly locked.
