### ISSUE TITLE
[has-source] No source code

### ISSUE THREAD

**Issue by jodeck80** [SoftwareEngineeringToolDemos/FSE-2014-ConceptCloud#3]
Criteria for issue:

Does the project contain source code? [has-source]

Source code for ConceptCloud does not appear to be available.

**Comment by gauri145** [comment]
The source code option has been already marked with a cross indicating that the authors have not provided the source code for this tool.

**Comment by gauri145** [comment]
When we asked the authors of the tool for the source code they replied stating that they have not obtained permission from the University, regarding the Intellectual Property, that they would need in order to do this.
