### ISSUE TITLE
[internal-source] Missing internal source

### ISSUE THREAD

**Issue by jodeck80** [SoftwareEngineeringToolDemos/FSE-2014-ConceptCloud#7]
Criteria for issue:

Does the readme link to source in this repo?
This should not apply since source code in unavailable, but an issue should be opened to document it. It can be closed with rationale explaining the issue.

**Comment by gauri145** [comment]
When we asked the authors of the tool for the source code they replied stating that they have not obtained permission from the University, regarding the Intellectual Property, that they would need in order to do this.
